#![allow(
    non_camel_case_types,
    clippy::enum_variant_names,
    clippy::too_many_arguments,
    clippy::upper_case_acronyms,
    clippy::type_complexity,
    dead_code
)]
use super::super::super::super::typings::database::get_or_init_postgres_client;
use super::super::super::super::typings::networks::get_provider_cache_for_network;
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.
use super::mainnet_inbox_abi_gen::RindexerMainnetInboxGen::{
    self, RindexerMainnetInboxGenEvents, RindexerMainnetInboxGenInstance,
};
use alloy::network::AnyNetwork;
use alloy::primitives::{Address, Bytes, B256};
use alloy::sol_types::{SolEvent, SolEventInterface, SolType};
use rindexer::{
    async_trait,
    blockclock::BlockClock,
    event::{
        callback_registry::{
            EventCallbackRegistry, EventCallbackRegistryInformation, EventCallbackResult,
            EventResult, HasTxInformation, TxInformation,
        },
        contract_setup::{ContractInformation, NetworkContract},
    },
    generate_random_id,
    manifest::{
        contract::{Contract, ContractDetails},
        yaml::read_manifest,
    },
    provider::{JsonRpcCachedProvider, RindexerProvider},
    AsyncCsvAppender, FutureExt, PostgresClient,
};
use std::collections::HashMap;
use std::error::Error;
use std::future::Future;
use std::path::{Path, PathBuf};
use std::pin::Pin;
use std::{any::Any, sync::Arc};

pub type AdminChangedData = RindexerMainnetInboxGen::AdminChanged;

#[derive(Debug, Clone)]
pub struct AdminChangedResult {
    pub event_data: AdminChangedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for AdminChangedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BatchProposedData = RindexerMainnetInboxGen::BatchProposed;

#[derive(Debug, Clone)]
pub struct BatchProposedResult {
    pub event_data: BatchProposedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BatchProposedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BatchesProvedData = RindexerMainnetInboxGen::BatchesProved;

#[derive(Debug, Clone)]
pub struct BatchesProvedResult {
    pub event_data: BatchesProvedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BatchesProvedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BatchesVerifiedData = RindexerMainnetInboxGen::BatchesVerified;

#[derive(Debug, Clone)]
pub struct BatchesVerifiedResult {
    pub event_data: BatchesVerifiedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BatchesVerifiedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BeaconUpgradedData = RindexerMainnetInboxGen::BeaconUpgraded;

#[derive(Debug, Clone)]
pub struct BeaconUpgradedResult {
    pub event_data: BeaconUpgradedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BeaconUpgradedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BondCreditedData = RindexerMainnetInboxGen::BondCredited;

#[derive(Debug, Clone)]
pub struct BondCreditedResult {
    pub event_data: BondCreditedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BondCreditedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BondDebitedData = RindexerMainnetInboxGen::BondDebited;

#[derive(Debug, Clone)]
pub struct BondDebitedResult {
    pub event_data: BondDebitedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BondDebitedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BondDepositedData = RindexerMainnetInboxGen::BondDeposited;

#[derive(Debug, Clone)]
pub struct BondDepositedResult {
    pub event_data: BondDepositedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BondDepositedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BondWithdrawnData = RindexerMainnetInboxGen::BondWithdrawn;

#[derive(Debug, Clone)]
pub struct BondWithdrawnResult {
    pub event_data: BondWithdrawnData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BondWithdrawnResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type ConflictingProofData = RindexerMainnetInboxGen::ConflictingProof;

#[derive(Debug, Clone)]
pub struct ConflictingProofResult {
    pub event_data: ConflictingProofData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for ConflictingProofResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type InitializedData = RindexerMainnetInboxGen::Initialized;

#[derive(Debug, Clone)]
pub struct InitializedResult {
    pub event_data: InitializedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for InitializedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type OwnershipTransferStartedData = RindexerMainnetInboxGen::OwnershipTransferStarted;

#[derive(Debug, Clone)]
pub struct OwnershipTransferStartedResult {
    pub event_data: OwnershipTransferStartedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for OwnershipTransferStartedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type OwnershipTransferredData = RindexerMainnetInboxGen::OwnershipTransferred;

#[derive(Debug, Clone)]
pub struct OwnershipTransferredResult {
    pub event_data: OwnershipTransferredData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for OwnershipTransferredResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type PausedData = RindexerMainnetInboxGen::Paused;

#[derive(Debug, Clone)]
pub struct PausedResult {
    pub event_data: PausedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for PausedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type Stats1UpdatedData = RindexerMainnetInboxGen::Stats1Updated;

#[derive(Debug, Clone)]
pub struct Stats1UpdatedResult {
    pub event_data: Stats1UpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for Stats1UpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type Stats2UpdatedData = RindexerMainnetInboxGen::Stats2Updated;

#[derive(Debug, Clone)]
pub struct Stats2UpdatedResult {
    pub event_data: Stats2UpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for Stats2UpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type UnpausedData = RindexerMainnetInboxGen::Unpaused;

#[derive(Debug, Clone)]
pub struct UnpausedResult {
    pub event_data: UnpausedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for UnpausedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type UpgradedData = RindexerMainnetInboxGen::Upgraded;

#[derive(Debug, Clone)]
pub struct UpgradedResult {
    pub event_data: UpgradedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for UpgradedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

#[async_trait]
trait EventCallback {
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()>;
}

pub struct EventContext<TExtensions>
where
    TExtensions: Send + Sync,
{
    pub database: Arc<PostgresClient>,
    pub csv: Arc<AsyncCsvAppender>,
    pub extensions: Arc<TExtensions>,
}

// didn't want to use option or none made harder DX
// so a blank struct makes interface nice
pub struct NoExtensions {}
pub fn no_extensions() -> NoExtensions {
    NoExtensions {}
}

pub fn batchproposed_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> BatchProposedEventCallbackType<TExtensions>
where
    BatchProposedResult: Clone + 'static,
    F: for<'a> Fn(Vec<BatchProposedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type BatchProposedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<BatchProposedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct BatchProposedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: BatchProposedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> BatchProposedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        BatchProposedResult: Clone + 'static,
        F: for<'a> Fn(Vec<BatchProposedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        let csv = AsyncCsvAppender::new(
            r"/Users/leopat/Documents/work/taiko-reth-fork/driver/generated_csv/MainnetInbox/mainnetinbox-batchproposed.csv",
        );
        if !Path::new(r"/Users/leopat/Documents/work/taiko-reth-fork/driver/generated_csv/MainnetInbox/mainnetinbox-batchproposed.csv").exists() {
            csv.append_header(vec!["contract_address".into(), "info_txs_hash".into(), "info_blocks_num_transactions".into(), "info_blocks_time_shift".into(), "info_blocks_signal_slots".into(), "info_blob_hashes".into(), "info_extra_data".into(), "info_coinbase".into(), "info_proposed_in".into(), "info_blob_created_in".into(), "info_blob_byte_offset".into(), "info_blob_byte_size".into(), "info_gas_limit".into(), "info_last_block_id".into(), "info_last_block_timestamp".into(), "info_anchor_block_id".into(), "info_anchor_block_hash".into(), "info_base_fee_config_adjustment_quotient".into(), "info_base_fee_config_sharing_pctg".into(), "info_base_fee_config_gas_issuance_per_second".into(), "info_base_fee_config_min_gas_excess".into(), "info_base_fee_config_max_gas_issuance_per_block".into(), "meta_info_hash".into(), "meta_proposer".into(), "meta_batch_id".into(), "meta_proposed_at".into(), "tx_list".into(), "tx_hash".into(), "block_number".into(), "block_hash".into(), "network".into(), "tx_index".into(), "log_index".into()].into())
                .await
                .expect("Failed to write CSV header");
        }

        Self {
            callback: batchproposed_handler(closure),
            context: Arc::new(EventContext {
                database: get_or_init_postgres_client().await,
                csv: Arc::new(csv),
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for BatchProposedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<BatchProposedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data.downcast::<BatchProposedData>().ok().map(|arc| {
                    BatchProposedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    }
                })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("BatchProposedEvent: Unexpected data type - expected: BatchProposedData")
        }
    }
}

pub enum MainnetInboxEventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    BatchProposed(BatchProposedEvent<TExtensions>),
}

pub async fn mainnet_inbox_contract(
    network: &str,
) -> RindexerMainnetInboxGenInstance<Arc<RindexerProvider>, AnyNetwork> {
    let address: Address =
        "0xaf95c030c7b8994ba9213b6a3964baa64e7df9d8".parse().expect("Invalid address");
    RindexerMainnetInboxGen::new(
        address,
        get_provider_cache_for_network(network).await.get_inner_provider(),
    )
}

pub async fn decoder_contract(
    network: &str,
) -> RindexerMainnetInboxGenInstance<Arc<RindexerProvider>, AnyNetwork> {
    if network == "ethereum" {
        RindexerMainnetInboxGen::new(
            // do not care about address here its decoding makes it easier to handle ValueOrArray
            Address::ZERO,
            get_provider_cache_for_network(network).await.get_inner_provider(),
        )
    } else {
        panic!("Network not supported");
    }
}

impl<TExtensions> MainnetInboxEventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    pub fn topic_id(&self) -> &'static str {
        match self {
            MainnetInboxEventType::BatchProposed(_) => {
                "0x9eb7fc80523943f28950bbb71ed6d584effe3e1e02ca4ddc8c86e5ee1558c096"
            }
        }
    }

    pub fn event_name(&self) -> &'static str {
        match self {
            MainnetInboxEventType::BatchProposed(_) => "BatchProposed",
        }
    }

    pub fn contract_name(&self) -> String {
        "MainnetInbox".to_string()
    }

    async fn get_provider(&self, network: &str) -> Arc<JsonRpcCachedProvider> {
        get_provider_cache_for_network(network).await
    }

    fn decoder(
        &self,
        network: &str,
    ) -> Arc<dyn Fn(Vec<B256>, Bytes) -> Arc<dyn Any + Send + Sync> + Send + Sync> {
        let decoder_contract = decoder_contract(network);

        match self {
            MainnetInboxEventType::BatchProposed(_) => {
                Arc::new(move |topics: Vec<B256>, data: Bytes| {
                    match BatchProposedData::decode_raw_log(topics, &data[0..]) {
                        Ok(event) => {
                            let result: BatchProposedData = event;
                            Arc::new(result) as Arc<dyn Any + Send + Sync>
                        }
                        Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                    }
                })
            }
        }
    }

    pub async fn register(self, manifest_path: &PathBuf, registry: &mut EventCallbackRegistry) {
        let rindexer_yaml = read_manifest(manifest_path).expect("Failed to read rindexer.yaml");
        let topic_id = self.topic_id();
        let contract_name = self.contract_name();
        let event_name = self.event_name();

        let contract_details = rindexer_yaml
            .all_contracts()
            .iter()
            .find(|c| c.name == contract_name)
            .unwrap_or_else(|| {
                panic!(
                    "Contract {} not found please make sure its defined in the rindexer.yaml",
                    contract_name
                )
            })
            .clone();

        let index_event_in_order = contract_details
            .index_event_in_order
            .as_ref()
            .map_or(false, |vec| vec.contains(&event_name.to_string()));

        // Expect providers to have been initialized, but it's an async init so this should
        // be fast but for correctness we must await each future.
        let mut providers = HashMap::new();
        for n in contract_details.details.iter() {
            let provider = self.get_provider(&n.network).await;
            providers.insert(n.network.clone(), provider);
        }

        let contract = ContractInformation {
            name: contract_details.before_modify_name_if_filter_readonly().into_owned(),
            details: contract_details
                .details
                .iter()
                .map(|c| {
                    let provider = providers.get(&c.network).expect("must have a provider").clone();

                    NetworkContract {
                        id: generate_random_id(10),
                        network: c.network.clone(),
                        cached_provider: provider.clone(),
                        block_clock: BlockClock::new(
                            rindexer_yaml.timestamps,
                            rindexer_yaml.config.timestamp_sample_rate,
                            provider.clone(),
                        ),
                        decoder: self.decoder(&c.network),
                        indexing_contract_setup: c.indexing_contract_setup(manifest_path),
                        start_block: c.start_block,
                        end_block: c.end_block,
                        disable_logs_bloom_checks: rindexer_yaml
                            .networks
                            .iter()
                            .find(|n| n.name == c.network)
                            .map_or(false, |n| n.disable_logs_bloom_checks.unwrap_or_default()),
                    }
                })
                .collect(),
            abi: contract_details.abi,
            reorg_safe_distance: contract_details.reorg_safe_distance.unwrap_or_default(),
        };

        let callback: Arc<
            dyn Fn(Vec<EventResult>) -> BoxFuture<'static, EventCallbackResult<()>> + Send + Sync,
        > = match self {
            MainnetInboxEventType::BatchProposed(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }
        };

        registry.register_event(EventCallbackRegistryInformation {
            id: generate_random_id(10),
            indexer_name: "driver".to_string(),
            event_name: event_name.to_string(),
            index_event_in_order,
            topic_id: topic_id.parse::<B256>().unwrap(),
            contract,
            callback,
        });
    }
}
